### ISSUE TITLE
Advertisement not centered

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#1600] opened 2021-01-15 17:46 UTC
Advertisement is no more centered on the left menu (seems to me it was not so long ago)
![image](https://user-images.githubusercontent.com/24532066/104759898-e0819e00-5760-11eb-8200-abe2e50a567b.png)

In my web navigator, I tried to put a class has-text-centered on the parent div but with no effect. I could not find margin nor padding, so I don't know how to solve this.
By the way, all elements in the area should be centered, so it would be "cleaner" if the class "has-text-centered" was applied on the parent div than for several children div.

**Comment by brunobesson** [comment] 2021-01-15 18:22
Duplicate of another one, fixes for next release.

**Closed by brunobesson** 2021-01-15 18:22 UTC
